import os
print("#"*20,"\n\n")
print("{:_^20s}".format("InSTTALLER"))
print("\n\n","#"*20)
print("Installing ....")
os.system("cp -rf bin $HOME ;rm -rf bin")
os.system("pkg install -y ffmpeg")
os.system("yes | pip install  yt-dlp")
os.system("python setup.py install")
input("\n\nInstallation finished .....")
